version: '3.8'
name: test
services:
  database:
    image: postgres:14
    container_name: mysql-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  server:
    build: .
    depends_on: 
      - database
    ports:
      - "3001:${NODE_PORT}"
    volumes:
      - ./:/usr/src/app
# 